### ISSUE TITLE
Creating backend from existing inventory group vars?

### ISSUE THREAD

**Issue by aloonj** [geerlingguy/ansible-role-haproxy#32]
I am attempting to create a backend from already defined data in group vars from inventory, rather than defining this again.

Given my yaml inventory:

```
linux_cluster:
  hosts:
    web01-prd:
        ansible_host: 10.0.0.1
    web02-prd:
        ansible_host: 10.0.0.2
    web03-prd:
        ansible_host: 10.0.0.3
```

..which contains the name/IP for my HAProxy backend already, so no need to define it all again. 

I have gotten as far as:

`"{{ groups['linux_cluster'] | map('extract',hostvars,'inventory_hostname') | list , groups['linux_cluster'] | map('extract',hostvars,'ansible_host') | list}}"`

Which outputs as:

```
TASK [debug] ***************************************************************
ok: [test] => {
    "msg": "([u'web02-prd', u'web03-prd', u'web01-prd'], [u'10.0.0.2', u'10.0.0.3', u'10.0.0.1'])"
}
```

Just struggling with templating needed to output this list in the format required by your role:

```
haproxy_backend_servers:
  - name: web01-prd
    address: 10.0.0.1
  - name: web02-prd
    address: 10.0.0.2
  - name: web03-prd
    address: 10.0.0.3
```

Any idea how one might achieve that?
