### ISSUE TITLE
Version detection on Ubuntu 22.04

### ISSUE THREAD

**Issue by danielsreichenbach** [geerlingguy/ansible-role-haproxy#50]
Using this role with default settings on Ubuntu 22.04 will cause an error when executing the `Set HAProxy version.` task due to the version reported by `haproxy -v` being different.

## What is happening

When querying the version - not sure if this is because of Ubuntu 22.04 or HAProxy 2.x - the version string will come back as

```
HAProxy version 2.4.14-1ubuntu1 2022/02/28 - https://haproxy.org/
```

## Fixing it

A temporary fix for the would be to simply modify the task to look for a different version string like

```yaml
- name: Set HAProxy version.
  set_fact:
    haproxy_version: '{{ haproxy_version_result.stdout_lines[0] | regex_replace("^HAProxy version ([0-9]\.[0-9]).*$", "\1") }}'
```

If the HAProxy version string is different between versions, it might be an idea to have variables per OS-Release to parse this.
